//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beutl.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TutorialStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TutorialStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beutl.Language.TutorialStrings", typeof(TutorialStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn the basics of Beutl.
        /// </summary>
        public static string LearnBeutlBasics {
            get {
                return ResourceManager.GetString("LearnBeutlBasics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No tutorials available.
        /// </summary>
        public static string NoTutorialsAvailable {
            get {
                return ResourceManager.GetString("NoTutorialsAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Tutorial.
        /// </summary>
        public static string StartTutorial {
            get {
                return ResourceManager.GetString("StartTutorial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn advanced animation editing using the graph editor.
        /// </summary>
        public static string Tutorial_AnimationEdit_Description {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the element you want to animate in the timeline..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step1_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step1_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an Object.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step1_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step1_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click the menu icon on the Y property and select &quot;Edit animation&quot;..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step10_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step10_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable Y Animation.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step10_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step10_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right-click on the Y property&apos;s graph editor and select &quot;Paste&quot; to apply the copied animation..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step11_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step11_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paste Animation.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step11_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step11_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press the Play button again to verify that X and Y animations work together..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step12_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step12_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Final Preview.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step12_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step12_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have learned advanced animation editing using the graph editor, applying easing functions, and copying/pasting animations. Explore more features on your own!.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step13_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step13_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tutorial Complete!.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step13_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step13_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click the + button on the Transform property and add &quot;Translate&quot;..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step2_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step2_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Translate.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step2_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step2_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click the menu icon on the X property and select &quot;Edit animation&quot;..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step3_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step3_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable X Animation.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step3_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step3_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The playback position has been moved forward. Click the diamond icon to add a keyframe at this position..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step4_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step4_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a Keyframe.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step4_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step4_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dragging an easing function from the Library panel (Easing tab) and dropping it onto the Graph Editor adds keyframes using that easing function. Dropping it at the same position as an existing keyframe changes the easing function of that keyframe..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step5_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step5_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply Easing.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step5_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step5_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In the graph editor, round icons represent easing control points. Move them left or right to reveal the diamond icons (keyframes) below..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step6_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step6_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Graph Editor Overview.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step6_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step6_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can drag diamond icons to change the time and value of keyframes..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step7_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step7_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move Keyframes.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step7_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step7_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press the Play button to preview your animation..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step8_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step8_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview Animation.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step8_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step8_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right-click on the graph editor background and select &quot;Copy All&quot; to copy all keyframes..
        /// </summary>
        public static string Tutorial_AnimationEdit_Step9_Content {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step9_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy Animation.
        /// </summary>
        public static string Tutorial_AnimationEdit_Step9_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Step9_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Animation Editing.
        /// </summary>
        public static string Tutorial_AnimationEdit_Title {
            get {
                return ResourceManager.GetString("Tutorial_AnimationEdit_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn to add elements, edit properties, and create animations.
        /// </summary>
        public static string Tutorial_SceneEdit_Description {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right-click on the timeline and add an ellipse element. You can also drag and drop from the library..
        /// </summary>
        public static string Tutorial_SceneEdit_Step1_Content {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step1_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add an Ellipse.
        /// </summary>
        public static string Tutorial_SceneEdit_Step1_Title {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step1_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click on the element you just added in the timeline to select it..
        /// </summary>
        public static string Tutorial_SceneEdit_Step2_Content {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step2_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the Element.
        /// </summary>
        public static string Tutorial_SceneEdit_Step2_Title {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step2_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is the properties tab. You can view and edit the properties of the selected element here..
        /// </summary>
        public static string Tutorial_SceneEdit_Step3_Content {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step3_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Tutorial_SceneEdit_Step3_Title {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step3_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find the Width property and click the menu icon next to it to enable animation. You can enable it with &quot;Edit animation&quot; or &quot;Edit animation in inline view&quot;.
        /// </summary>
        public static string Tutorial_SceneEdit_Step4_Content {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step4_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable Animation.
        /// </summary>
        public static string Tutorial_SceneEdit_Step4_Title {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step4_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The playback position has been moved forward. Click the diamond icon to add a keyframe at this position..
        /// </summary>
        public static string Tutorial_SceneEdit_Step5_Content {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step5_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a Keyframe.
        /// </summary>
        public static string Tutorial_SceneEdit_Step5_Title {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step5_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Width value has been changed to 300. This creates an animation from 100 to 300 over time..
        /// </summary>
        public static string Tutorial_SceneEdit_Step6_Content {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step6_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change the Value.
        /// </summary>
        public static string Tutorial_SceneEdit_Step6_Title {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step6_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press the Play button in the player to preview your animation..
        /// </summary>
        public static string Tutorial_SceneEdit_Step7_Content {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step7_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview the Animation.
        /// </summary>
        public static string Tutorial_SceneEdit_Step7_Title {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step7_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have learned how to add elements, edit properties, and create animations. Explore more features on your own!.
        /// </summary>
        public static string Tutorial_SceneEdit_Step8_Content {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step8_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tutorial Complete!.
        /// </summary>
        public static string Tutorial_SceneEdit_Step8_Title {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Step8_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scene Editing Basics.
        /// </summary>
        public static string Tutorial_SceneEdit_Title {
            get {
                return ResourceManager.GetString("Tutorial_SceneEdit_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Beutl is a cross-platform video editor. This tutorial will guide you through the basics..
        /// </summary>
        public static string Tutorial_Welcome_Content {
            get {
                return ResourceManager.GetString("Tutorial_Welcome_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click here to create a new project or scene to start editing..
        /// </summary>
        public static string Tutorial_Welcome_Create_Content {
            get {
                return ResourceManager.GetString("Tutorial_Welcome_Create_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Tutorial_Welcome_Create_Title {
            get {
                return ResourceManager.GetString("Tutorial_Welcome_Create_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The menu bar contains options for file management, editing, and more..
        /// </summary>
        public static string Tutorial_Welcome_MenuBar_Content {
            get {
                return ResourceManager.GetString("Tutorial_Welcome_MenuBar_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu Bar.
        /// </summary>
        public static string Tutorial_Welcome_MenuBar_Title {
            get {
                return ResourceManager.GetString("Tutorial_Welcome_MenuBar_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to Beutl.
        /// </summary>
        public static string Tutorial_Welcome_Title {
            get {
                return ResourceManager.GetString("Tutorial_Welcome_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string TutorialFinish {
            get {
                return ResourceManager.GetString("TutorialFinish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string TutorialNext {
            get {
                return ResourceManager.GetString("TutorialNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string TutorialPrevious {
            get {
                return ResourceManager.GetString("TutorialPrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip Tutorial.
        /// </summary>
        public static string TutorialSkip {
            get {
                return ResourceManager.GetString("TutorialSkip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        public static string TutorialStep {
            get {
                return ResourceManager.GetString("TutorialStep", resourceCulture);
            }
        }
    }
}
